### ISSUE TITLE
[Global Offset] 👀Option to adjust offset from the options menu

### ISSUE THREAD

**Issue by Sereni** [Sereni/Simply-Love-SM5#4]
Like Groovenights had it! Should go in 1 ms increments. Indicate whether the change makes it earlier or later.

**Comment by Sereni** [comment]
If we do the option, changing offset via F keys should probably become the source of truth? If the owners want to change default offset without going to the metrics.

**Comment by Fieoner** [comment]
https://github.com/Sereni/Simply-Love-SM5/pull/7
